export const cities = [
    "New York City",
    "Tokyo",
    "London",
    "Paris",
    "Los Angeles",
    "Sydney",
    "Dubai",
    "Rio de Janeiro",
    "Beijing",
    "Rome",
    "Moscow",
    "Toronto",
    "Mumbai",
    "Cape Town",
    "Berlin",
    "Seoul",
    "Istanbul",
    "Bangkok",
    "Mexico City",
    "Amsterdam",
    "San Francisco",
    "Barcelona",
    "Singapore",
    "Stockholm",
    "Dublin"
]
